# Cloud Build config for building and pushing my container to Artifact Registry
# I'm keeping it very simple for now: build + push only
# Later I can add steps for tests, Terraform, or even deploy

steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE}",
        "."
      ]

  # Step 2: Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE}"
      ]

images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE}"

substitutions:
  # Default values – I can override them in the trigger UI
  _REGION: "europe-west1"
  _REPO: "order-tracking"
  _IMAGE: "order-tracking:latest"
