# ===================== local-h2 =====================
spring:
  config:
    activate:
      on-profile: local-h2

  datasource:
    url: jdbc:h2:mem:demo;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    # Con H2 usa su propio dialecto para evitar warnings
    database-platform: org.hibernate.dialect.H2Dialect

  kafka:
    # Redpanda local, sin seguridad
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:19092}

---
# ===================== local-pg =====================
spring:
  config:
    activate:
      on-profile: local-pg

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orders}
    username: ${SPRING_DATASOURCE_USERNAME:orders}
    password: ${SPRING_DATASOURCE_PASSWORD:orders_strong}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    # Redpanda local, sin seguridad
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
