spring:
  application:
    name: order-tracking

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

  kafka:
    producer:
      acks: all
      retries: 10
      properties:
        enable.idempotence: true
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-tracking-processor
      auto-offset-reset: latest
      properties:
        isolation.level: read_committed
        spring.json.trusted.packages: "com.egobb.*"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      ack-mode: RECORD

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
