spring:
  application:
    name: order-tracking
  datasource:
    url: jdbc:h2:mem:demo;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
---
spring:
  config:
    activate:
      on-profile: pg
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: orders
    password: orders
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
