version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports: ["8081:8080"]
  app:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    image: ghcr.io/egobb/order-tracking:latest
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=pg \
        -Dspring.datasource.url=jdbc:postgresql://db:5432/${POSTGRES_DB}
    depends_on:
      - db
volumes:
  pgdata:
