version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports: ["8081:8080"]
volumes:
  pgdata:
