name: Format check
on:
  pull_request:
    branches: [develop, main]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Run formatter (spotless:apply) and fail if diffs
        run: |
          ./app/mvnw -f app/pom.xml -q spotless:apply
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          if [ -n "$(git status --porcelain)" ]; then
            echo "::error::El formato no está aplicado. Ejecuta 'make fmt' y sube los cambios."
            git --no-pager diff --name-only
            exit 1
          fi
