name: Release JAR
on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Package (skip tests)
        run: ./app/mvnw -f app/pom.xml -B -DskipTests package
      - name: Create GitHub Release and upload JAR
        uses: softprops/action-gh-release@v2
        with:
          files: app/target/*.jar
          generate_release_notes: true
