name: PR Title (Conventional Commits)

on:
  pull_request_target:
    branches: [develop, main]
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: read
  statuses: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            docs
            refactor
            perf
            test
            build
            ci
            revert
            release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
